export const ADDEXPENSE = "ADDEXPENSE";
export const EDITEXPENSE = "EDITEXPENSE";
export const DELETEEXPENSE = "DELETEEXPENSE";

export const ADDINCOME = "ADDINCOME";
export const EDITINCOME = "EDITINCOME";
export const DELETEINCOME = "DELETEINCOME";

export const LOCALSTORAGEKEY = "LOCALSTORAGEKEY";
