export const ADDEXPENSE = "ADDEXPENSE";
export const DELETEEXPENSE = "DELETEEXPENSE";

export const ADDINCOME = "ADDINCOME";
export const DELETEINCOME = "DELETEINCOME";

export const EDITFORM = "EDITFORM";
export const CLEARFORM = "CLEARFORM";

export const UPDATEHISTORY = "UPDATEHISTORY";

export const LOCALSTORAGEKEY = "LOCALSTORAGEKEY";
